sudo: required
language: generic
dist: bionic

services:
  - docker

matrix:
  include:
    - name: "Xenial kinetic LLVM"
      env: ROS_DISTRO=kinetic_llvm
    - name: "Bionic melodic LLVM"
      env: ROS_DISTRO=melodic_llvm
    - name: "Bionic melodic"
      env: ROS_DISTRO=melodic
    - name: "Focal Fossa noetic"
      env: ROS_DISTRO=noetic
    - name: "Focal Fossa noetic LLVM"
      env: ROS_DISTRO=noetic_llvm

script:
  - docker build -f ./docker/$ROS_DISTRO/Dockerfile .
